# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('timestamp', unixtimestampfield.fields.UnixTimeStampField()),
                ('transaction_currency', models.CharField(max_length=6)),
                ('counter_currency', models.CharField(max_length=6)),
                ('signal', models.CharField(max_length=15, null=True)),
                ('trend', models.CharField(max_length=15, null=True)),
                ('strength_value', models.IntegerField(null=True)),
                ('strength_max', models.IntegerField(null=True)),
                ('price', models.BigIntegerField()),
                ('rsi_value', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
