# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('exchange', models.IntegerField(choices=[(0, 'BITTREX'), (1, 'BINANCE'), (2, 'KUCOIN'), (3, 'TDAX')])),
                ('api_key_encrypted', models.CharField(default='', max_length=200)),
                ('api_secret_encrypted', models.CharField(default='', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
